import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';

/**
 * A frozen per-beneficiary commission line for a sale, generated by the
 * `sync_sale_commission_splits` trigger from the org catalog at sale time.
 */
export interface SaleCommissionSplit {
  id: string;
  sale_id: string;
  user_id: string;
  product_name: string | null;
  source: 'user' | 'profile';
  basis: 'fixed' | 'pct';
  rate: number;
  amount: number;
}

/** Splits of a single sale, for the sale detail view. */
export function useSaleCommissionSplits(saleId?: string | null) {
  const { organization } = useAuth();
  const orgId = organization?.id;

  return useQuery<SaleCommissionSplit[]>({
    queryKey: ['sale-commission-splits', saleId],
    queryFn: async () => {
      if (!saleId) return [];
      const { data, error } = await (supabase as any)
        .from('sale_commission_splits')
        .select('id, sale_id, user_id, product_name, source, basis, rate, amount')
        .eq('sale_id', saleId);
      if (error) throw error;
      return (data || []) as SaleCommissionSplit[];
    },
    enabled: !!orgId && !!saleId,
  });
}

/**
 * Splits for many sales at once, keyed by sale_id. Used by the commission
 * screens, which need to turn one sale into several beneficiaries.
 *
 * Sales with no splits are simply absent from the map, and callers keep their
 * existing single-commercial behaviour for those.
 */
export async function fetchSplitsBySale(
  saleIds: string[],
): Promise<Map<string, SaleCommissionSplit[]>> {
  const bySale = new Map<string, SaleCommissionSplit[]>();
  if (saleIds.length === 0) return bySale;

  const { data, error } = await (supabase as any)
    .from('sale_commission_splits')
    .select('id, sale_id, user_id, product_name, source, basis, rate, amount')
    .in('sale_id', saleIds);
  if (error) throw error;

  for (const row of (data || []) as SaleCommissionSplit[]) {
    const list = bySale.get(row.sale_id) || [];
    list.push(row);
    bySale.set(row.sale_id, list);
  }
  return bySale;
}
