// This file is automatically generated. Do not edit it directly.
// EXCEPTION: the `safeLock` / `authTimeoutFetch` hardening below is hand-written
// and MUST be preserved across regenerations. Without it the app deadlocks on the
// browser Web Lock that Supabase uses to coordinate token refresh (see comments).
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// --- Web Lock hardening -----------------------------------------------------
// supabase-js coordinates token refresh across tabs with `navigator.locks`. Its
// default waits for the lock FOREVER (acquireTimeout === -1). If a tab dies while
// holding the lock, or a refresh request hangs, every subsequent auth call
// (getSession, refreshSession, the AuthContext listener) blocks indefinitely →
// the app shows an infinite spinner until you clear storage or open incognito.
// This wrapper caps the wait and, on timeout, runs WITHOUT the lock instead of
// freezing. Worst case is a rare duplicate refresh (recoverable); far better than
// a permanent deadlock.
const safeLock = async <R>(
  name: string,
  acquireTimeout: number,
  fn: () => Promise<R>,
): Promise<R> => {
  const locks = (typeof navigator !== 'undefined' ? (navigator as any).locks : undefined);
  if (!locks?.request) {
    // Older browser / non-DOM context: no lock available, just run.
    return await fn();
  }

  const cap = acquireTimeout > 0 ? acquireTimeout : 5000;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), cap);

  try {
    return await locks.request(
      name,
      { mode: 'exclusive', signal: controller.signal },
      async () => await fn(),
    );
  } catch (e: any) {
    // AbortError = could not acquire the lock within `cap` ms (stuck holder).
    // Proceed without it rather than hang the whole app.
    if (e?.name === 'AbortError') {
      return await fn();
    }
    throw e;
  } finally {
    clearTimeout(timer);
  }
};

// --- Auth fetch timeout -----------------------------------------------------
// Belt-and-suspenders for the lock fix above: cap ONLY auth requests so a hung
// token refresh can't hold the lock (or accumulate sockets) forever. Storage
// uploads, edge functions and REST are passed through untouched — they can
// legitimately run long.
const AUTH_FETCH_TIMEOUT_MS = 15000;
const authTimeoutFetch: typeof fetch = (input, init) => {
  const url =
    typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;

  if (!url || !url.includes('/auth/v1/')) {
    return fetch(input, init);
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), AUTH_FETCH_TIMEOUT_MS);

  let signal: AbortSignal = controller.signal;
  if (init?.signal) {
    try {
      signal = (AbortSignal as any).any([init.signal, controller.signal]);
    } catch {
      signal = controller.signal;
    }
  }

  return fetch(input, { ...init, signal }).finally(() => clearTimeout(timer));
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: safeLock,
  },
  global: {
    fetch: authTimeoutFetch,
  },
});
